version: '3.9'

services:
  workspace:
    container_name: hell-world-workspace
    image: docker.io/aprilsea/ubuntu-java
    tty: true
    volumes:
      - /home/phuckool/aprilsea/java/gs-spring-boot/initial:/home/vscode/workspace:cached
    ports:
      - 5555:5555